version: '3.4'
volumes:
  solr-data:
  le-data:
  # index_test_solr-data:
  #   external: true
      
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
  solr:
    internal: true
services:
  nginx-proxy:
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    #image: "repository.staging.derilinx.com/nginx-proxy:$IMAGE_TAG"
    image: "nginxproxy/nginx-proxy:latest"
    networks:
      default:
        aliases:
          - $HOST
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf"
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/ssl/certs:/etc/nginx/certs"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/htpasswd:/etc/nginx/htpasswd"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  letsencrypt-nginx-proxy-companion:
    #image: "repository.staging.derilinx.com/letsencrypt-nginx-proxy-companion:$IMAGE_TAG"
    image: "nginxproxy/acme-companion"
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - "./nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf"
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/ssl/certs:/etc/nginx/certs"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/htpasswd:/etc/nginx/htpasswd"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "le-data:/etc/acme.sh"
    depends_on:
      - nginx-proxy


  # webservice:
  #   restart: on-failure
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: 50m
  #   networks:
  #     default:
  #     solr:
  #   environment:
  #     - VIRTUAL_HOST=${HOST}
  #     - VIRTUAL_PROTO=uwsgi
  #     - LETSENCRYPT_HOST=${HOST}
  #     - LETSENCRYPT_EMAIL="dev@derilinx.com"


  api:
    build:
      context: ./api/api
      dockerfile: Dockerfile
    networks:
      default:
      solr:
    volumes:
      # that's a lot of api
      - "./api/api/api:/usr/src/app/api"
    environment:
      - SOLR_URL=http://solr:8983/solr/ckan
      - VIRTUAL_HOST=api.${HOST}
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=api.${HOST}
      - LETSENCRYPT_EMAIL="dev@derilinx.com"

  web:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    networks:
      default:
    environment:
      - REACT_APP_DATA_SERVICE_URL=http://api.${HOST}
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL="dev@derilinx.com"
    volumes:
      - "./frontend/frontend/public:/app/public"
      - "./frontend/frontend/src:/app/src"

  solr:
    #image: "repository.staging.derilinx.com/solr_8.8:$IMAGE_TAG"
    image: "solr:8"
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    networks:
      solr:
    environment:
      - SOLR_JAVA_MEM=-Xms1g -Xmx1g
      - SOLR_OPTS=-Dlog4j2.formatMsgNoLookups=true
    volumes:
      - "./api/solr:/var/solr/data/ckan/"
      - solr-data:/var/solr/data/ckan/data:rw
#      - index_test_solr-data:/tmp/old-data

#
