volumes:
  solr-data:
  le-data:
  # index_test_solr-data:
  #    external: true
  dagster-postgres:
    driver: local

networks:
  default:
    driver: bridge
    # this is only required in openvswitch networks.
    driver_opts:
      com.docker.network.driver.mtu: 1400
  solr:
    internal: true
  solrbridge:
    driver: host
  dagster_host:

services:
  nginx-proxy:
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    image: "nginxproxy/nginx-proxy:latest"
    networks:
      default:
        aliases:
          - $HOST
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf"
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/ssl/certs:/etc/nginx/certs"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/htpasswd:/etc/nginx/htpasswd"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: "nginxproxy/acme-companion"
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - ACME_CA_URI=${ACME_CA_URI}
    volumes:
      - "./nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf"
      - "./nginx/vhost.d:/etc/nginx/vhost.d"
      - "./nginx/ssl/certs:/etc/nginx/certs"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/htpasswd:/etc/nginx/htpasswd"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      # custom certificates
      # see https://github.com/nginx-proxy/acme-companion/blob/main/docs/Standalone-certificates.md
      # if you need this, please edit the letsencrypt_user_data.conf file accordingly
      # and add a vhost to the proxy.conf file
      - "./nginx/conf.d/letsencrypt_user_data.conf:/app/letsencrypt_user_data:ro"
      - "le-data:/etc/acme.sh"
    depends_on:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-size: 50m

  api:
    restart: always
    build:
      context: ./api/api
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    networks:
      default:
      solr:
    volumes:
      # that's a lot of api
      - "./api/api/api:/usr/src/app/api"
    environment:
      - SOLR_URL=http://solr:8983/solr/ckan
      - VIRTUAL_HOST=api.${HOST}
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=api.${HOST}
      - LETSENCRYPT_EMAIL="it@iode.org"

  web:
    restart: always
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    networks:
      default:
    environment:
      - REACT_APP_DATA_SERVICE_URL=https://api.${HOST}
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=${HOST}
      - LETSENCRYPT_EMAIL="it@iode.org"
    volumes:
      - "./frontend/frontend/public:/app/public"
      - "./frontend/frontend/src:/app/src"

  indexer:
    #removed the start always, as this is running again and again
    #restart: always
    build:
      context: ./indexer/indexer
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    networks:
      solr:
    volumes:
      - "./indexer/indexer:/usr/src/app"
      - "./source-data:/opt/data"
    environment:
      - SOLR_URL=http://solr:8983/solr/ckan
      # needs to match the volume mount
      - DATA_DIR=/opt/data

  solr:
    restart: always
    image: "solr:8"
    ports:
      - "8983:8983"
    logging:
      driver: "json-file"
      options:
        max-size: 50m
    networks:
      solr:
    environment:
      - SOLR_JAVA_MEM=-Xms1g -Xmx1g
      - SOLR_OPTS=-Dlog4j2.formatMsgNoLookups=true
    volumes:
      - "./api/solr:/var/solr/data/ckan/"
      - solr-data:/var/solr/data/ckan/data:rw
      - "./api/solr/sample-solr-data/:/var/solr/data/ckan/data/index"

  # This is for a single dagster instance, that does not use an externally defined network
  # this NEEDS following environment variables from the .env file
  # $HOST (already defined)
  # $PROJECT default eco
  # CONTAINER_TAG default latest

  dagster-dagit:
    restart: always
    image: "docker.io/nsfearthcube/dagster-${PROJECT:-eco}:${CONTAINER_TAG:-latest}"
    environment: &env
      - DEBUG=${DEBUG:-false}
      - PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
      - PORTAINER_URL=${PORTAINER_URL}
      - PORTAINER_KEY=${PORTAINER_KEY}
      - GLEANERIO_GLEANER_IMAGE=${GLEANERIO_GLEANER_IMAGE}
      - GLEANERIO_NABU_IMAGE=${GLEANERIO_NABU_IMAGE}
      - GLEANERIO_LOG_PREFIX=${GLEANERIO_LOG_PREFIX}
      - GLEANER_MINIO_ADDRESS=${GLEANERIO_MINIO_ADDRESS}
      - GLEANER_MINIO_PORT=${GLEANERIO_MINIO_PORT}
      - GLEANER_MINIO_USE_SSL=${GLEANERIO_MINIO_USE_SSL}
      - GLEANER_MINIO_BUCKET=${GLEANERIO_MINIO_BUCKET}
      - GLEANER_MINIO_ACCESS_KEY=${GLEANERIO_MINIO_ACCESS_KEY}
      - GLEANER_MINIO_SECRET_KEY=${GLEANERIO_MINIO_SECRET_KEY}
      - GLEANER_HEADLESS_ENDPOINT=${GLEANERIO_HEADLESS_ENDPOINT}
      - GLEANER_HEADLESS_NETWORK=${GLEANERIO_HEADLESS_NETWORK}
      - GLEANER_GRAPH_URL=${GLEANERIO_GRAPH_URL}
      - GLEANER_GRAPH_NAMESPACE=${GLEANERIO_GRAPH_NAMESPACE}
      - GLEANERIO_NABU_CONFIG_PATH=${GLEANERIO_NABU_CONFIG_PATH:-/configs/gleaner/nabuconfig.yaml}
      - GLEANERIO_GLEANER_CONFIG_PATH=${GLEANERIO_GLEANER_CONFIG_PATH:-/configs/gleaner/gleanerconfig.yaml}
      - GLEANERIO_NABU_DOCKER_CONFIG=${GLEANERIO_NABU_DOCKER_CONFIG:-nabu}
      - GLEANERIO_GLEANER_DOCKER_CONFIG=${GLEANERIO_GLEANER_DOCKER_CONFIG:-gleaner}
      - VIRTUAL_HOST=workflow.${HOST}
      - VIRTUAL_PROTO=http
      - LETSENCRYPT_HOST=workflow.${HOST}
      - LETSENCRYPT_EMAIL="it@iode.org"
    ports:
      - 3000:3000
    networks:
      - dagster_host
    depends_on:
      - dagster-postgres

  dagster-daemon:
    restart: always
    image: docker.io/nsfearthcube/dagster-${PROJECT:-eco}:${CONTAINER_TAG:-latest}
    environment: *env
    command: "dagster-daemon run"
    depends_on:
      - dagster-postgres
    networks:
      - dagster_host

  dagster-postgres:
    restart: always
    image: postgres:13.3
    container_name: dagster-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
    networks:
      - dagster_host

  headless:
    # image: chromedp/headless-shell:stable
    # stable after 105 causes "devtool: CreateURL: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.",
    image: chromedp/headless-shell:105.0.5195.127
    restart: unless-stopped
    shm_size: "2gb"
    ports:
      - 9222:9222
    environment:
      - SERVICE_PORTS=9222

